import type { Node } from "../../../domain/index.js";

export const EXAMPLE = {
  contract_version: "1",
  stage: 1,
  brief: { product: "MagnaCalm glycinate 400mg", url: "https://…", market: "UK" },
  sources: [
    {
      id: "sha256:2f1a…",
      url: "https://reddit.com/r/insomnia/comments/9d1x",
      title: "Anyone else waking at 3am?",
      kind: "forum",
      publisher: "reddit.com",
      fetched_at: "2026-09-10T09:14:22Z",
      marketing: false,
      admitted: true,
      admission_reason: "forum — admitted by policy",
      archived: true,
      node: "review_mining",
    },
    {
      id: "sha256:7d5b…",
      url: "https://amazon.co.uk/product-reviews/B0C?filter=3star",
      title: "MagnaCalm reviews, 3 star",
      kind: "marketplace_review",
      publisher: "amazon.co.uk",
      fetched_at: "2026-09-10T09:20:11Z",
      marketing: false,
      admitted: true,
      admission_reason: "marketplace_review — admitted by policy",
      archived: true,
      node: "review_mining",
    },
    {
      id: "sha256:9c04…",
      url: "https://top10supplementpicks.net/best-magnesium",
      title: "Best magnesium 2026",
      kind: "seo_listicle",
      publisher: "top10supplementpicks.net",
      fetched_at: "2026-09-10T09:15:02Z",
      marketing: true,
      admitted: false,
      admission_reason: "seo_listicle — rejected by admission policy",
      archived: false,
      node: "competitors",
    },
    {
      id: "sha256:1c9d…",
      url: "https://magnacalm.example/products/glycinate-400",
      title: "MagnaCalm Magnesium Glycinate 400mg — 90 capsules",
      kind: "first_party",
      publisher: "magnacalm.example",
      fetched_at: "2026-09-10T09:11:40Z",
      marketing: true,
      admitted: true,
      admission_reason: "first_party — the product's own page",
      archived: true,
      node: "competitors",
    },
    {
      id: "sha256:5e21…",
      url: "https://calmwell.example/magnesium-glycinate",
      title: "CalmWell Magnesium Glycinate 400mg",
      kind: "competitor_marketing",
      publisher: "calmwell.example",
      fetched_at: "2026-09-10T09:16:05Z",
      marketing: true,
      admitted: true,
      admission_reason: "competitor_marketing — admitted by policy",
      archived: true,
      node: "competitors",
    },
    {
      id: "sha256:a803…",
      url: "https://sleepmist.example/magnesium-spray",
      title: "SleepMist Magnesium Glycinate Oral Spray",
      kind: "competitor_marketing",
      publisher: "sleepmist.example",
      fetched_at: "2026-09-10T09:17:30Z",
      marketing: true,
      admitted: true,
      admission_reason: "competitor_marketing — admitted by policy",
      archived: true,
      node: "competitors",
    },
    {
      id: "sha256:b112…",
      url: "https://trends.example/magnesium-glycinate-2023-2026",
      title: "Magnesium glycinate — monthly search volume, 2023–2026",
      kind: "keyword_data",
      publisher: "trends.example",
      fetched_at: "2026-09-10T09:22:03Z",
      marketing: false,
      admitted: true,
      admission_reason: "keyword_data — admitted by policy",
      archived: true,
      node: "category_data",
    },
    {
      id: "sha256:d4f7…",
      url: "https://www.facebook.com/ads/library/?id=1234567890",
      title: "CalmWell — 'Finally sleeping through' ad",
      kind: "ad_library",
      publisher: "facebook.com",
      fetched_at: "2026-09-10T09:18:44Z",
      first_seen: "2026-03-02",
      marketing: true,
      admitted: true,
      admission_reason: "ad_library — admitted by policy",
      archived: true,
      node: "competitors",
    },
  ],
  excerpts: [
    {
      id: "sha256:4b7e…",
      source_id: "sha256:2f1a…",
      text: "I wake up at 3am and can't get back to sleep. Every single night.",
      locator: { kind: "char_range", start: 4120, end: 4187 },
      captured_at: "2026-09-10T09:14:25Z",
      node: "review_mining",
      star_rating: null,
      posted_at: "2026-04-02",
      axis: "why_bought",
      themes: ["3am waking"],
    },
    {
      id: "sha256:e10c…",
      source_id: "sha256:7d5b…",
      text: "Took it for a week, felt nothing, cancelled. Turns out you need six weeks.",
      locator: { kind: "char_range", start: 812, end: 886 },
      captured_at: "2026-09-10T09:20:14Z",
      node: "review_mining",
      star_rating: 3,
      posted_at: "2026-05-19",
      axis: "why_quit",
      themes: ["time to effect"],
    },
  ],
  measurements: [
    {
      id: "m1",
      node: "category_data",
      metric: "search_volume",
      value: 1900000,
      unit: "searches/month",
      period: "2026-08",
      source_id: "sha256:b112…",
    },
  ],
  attributes: [
    {
      id: "a1",
      node: "product_data",
      key: "dose_per_serving",
      value: "400 mg",
      source_id: "sha256:1c9d…",
    },
    {
      id: "a2",
      node: "product_data",
      key: "third_party_lab_tested",
      value: "USP verified, batch 2026-07, certificate linked on page",
      source_id: "sha256:1c9d…",
    },
  ],
  competitor_reference: {
    name: "MagnaCalm Magnesium Glycinate 400mg",
    form: "capsule",
    form_as_printed: "90 vegan capsules",
    actives: ["magnesium glycinate"],
    source_id: "sha256:1c9d…",
  },
  competitors: [
    {
      id: "c1",
      name: "CalmWell Magnesium Glycinate 400mg",
      brand: "CalmWell",
      url: "https://calmwell.example/magnesium-glycinate",
      relation: "direct",
      form: "capsule",
      form_as_printed: "120 capsules",
      active_ingredients: [
        {
          name_as_printed: "Magnesium (as Magnesium Bisglycinate)",
          name_normalised: "magnesium glycinate",
          dose: "400",
          unit: "mg",
          per: "serving",
          standardisation: "",
        },
      ],
      shared_actives: ["magnesium glycinate"],
      dose_per_serving: "400 mg (2 capsules)",
      positioning_copy: "The gentle magnesium that lets you sleep through the night.",
      price: "£19.99",
      price_per_dose: "£0.33 per serving",
      source_id: "sha256:5e21…",
      ad_source_ids: ["sha256:d4f7…"],
    },
    {
      id: "c2",
      name: "SleepMist Magnesium Glycinate Oral Spray",
      brand: "SleepMist",
      url: "https://sleepmist.example/magnesium-spray",
      relation: "indirect",
      form: "spray",
      form_as_printed: "oral spray, 50 ml",
      active_ingredients: [
        {
          name_as_printed: "Magnesium Glycinate",
          name_normalised: "magnesium glycinate",
          dose: "100",
          unit: "mg",
          per: "serving",
          standardisation: "",
        },
      ],
      shared_actives: ["magnesium glycinate"],
      dose_per_serving: "100 mg (4 sprays)",
      positioning_copy: "Four sprays under the tongue. No pills to swallow.",
      price: "£14.00",
      price_per_dose: "",
      source_id: "sha256:a803…",
      ad_source_ids: [],
    },
  ],
  saturation: [
    {
      node: "review_mining",
      curve: [
        { source_id: "sha256:2f1a…", new_themes: 4, cumulative_themes: 4 },
        { source_id: "sha256:7d5b…", new_themes: 0, cumulative_themes: 11 },
      ],
      stopped_because: "three consecutive sources added no new theme",
    },
    {
      node: "competitors",
      class: "direct",
      curve: [
        { source_id: "sha256:5e21…", new_themes: 1, cumulative_themes: 1 },
        { source_id: "sha256:9c04…", new_themes: 0, cumulative_themes: 1 },
      ],
      stopped_because: "still finding direct brands when the example ends",
    },
    {
      node: "competitors",
      class: "indirect",
      curve: [{ source_id: "sha256:a803…", new_themes: 1, cumulative_themes: 1 }],
      stopped_because: "still finding indirect brands when the example ends",
    },
  ],
  nodes: [
    {
      node: "product_data",
      status: "incomplete",
      done_criterion_met: false,
      why: "9 of 10 attributes captured; no COA published",
    },
    {
      node: "category_data",
      status: "incomplete",
      done_criterion_met: false,
      why: "three-year trend captured; category size is a single point estimate",
    },
    {
      node: "review_mining",
      status: "complete",
      done_criterion_met: true,
      why: "saturated at 14 sources; 3-star coverage present",
    },
    {
      node: "competitors",
      status: "incomplete",
      done_criterion_met: false,
      why: "neither class had three consecutive sources with no new brand",
    },
  ],
  gaps: [
    {
      node: "competitors",
      missing: "CalmWell ad library returns no UK creative",
      would_need: "a UK-IP ad-library pull, or a manual capture",
      blocking: false,
    },
    {
      node: "product_data",
      missing: "no certificate of analysis published",
      would_need: "the brand to publish one, or a batch COA on request",
      blocking: false,
    },
    {
      node: "review_mining",
      missing: "forum coverage is thin outside Reddit",
      would_need: "a niche sleep board with a readable archive",
      blocking: false,
    },
  ],
};
