import pg from "pg";

import { Trace } from "../../trace/index.js";

/** What the shared SQL must become for Postgres: numbered parameters, identity keys, eight-byte floats, and counts read back as numbers. */
export class PostgresDialect {
  static readonly INT8 = 20;

  static statement(sql: string): string {
    Trace.tick(import.meta.url, "PostgresDialect.statement");
    let n = 0;
    return sql.replace(/'(?:[^']|'')*'|\?/g, (token) => (token === "?" ? `$${++n}` : token));
  }

  static script(ddl: string): string {
    Trace.line(import.meta.url, "PostgresDialect.script");
    return ddl
      .replace(/INTEGER PRIMARY KEY AUTOINCREMENT/g, "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
      .replace(/\bREAL\b/g, "DOUBLE PRECISION");
  }

  static parser(oid: number, format?: string): (value: string) => unknown {
    Trace.tick(import.meta.url, "PostgresDialect.parser");
    if (oid === PostgresDialect.INT8) return Number;
    return pg.types.getTypeParser(oid, format as "text");
  }
}
