import { readdirSync, readFileSync, writeFileSync, statSync, mkdirSync } from "node:fs";
import { dirname, join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";
import ts from "typescript";

const HERE = dirname(fileURLToPath(import.meta.url));
const SRC = join(HERE, "..", "src");
const OUT = join(HERE, "..", "..", "docs", "class-diagram.md");

const LAYER_ORDER = ["domain", "config", "extract", "adapters", "agent", "http"];

class Module {
  constructor(rel, source) {
    this.rel = rel;
    this.source = source;
    this.layer = rel.split(sep).length > 1 ? rel.split(sep)[0] : "(unlayered)";
  }

  get types() {
    const found = [];
    this.source.forEachChild((node) => {
      if (ts.isClassDeclaration(node) && node.name) {
        found.push(new TypeBox(node.name.text, "class", this.members(node), this.injected(node)));
      }
      if (ts.isInterfaceDeclaration(node)) {
        found.push(new TypeBox(node.name.text, "interface", this.members(node), []));
      }
    });
    return found;
  }

  members(node) {
    return node.members
      .filter((m) => ts.isMethodDeclaration(m) || ts.isMethodSignature(m))
      .filter((m) => !m.modifiers?.some((x) => x.kind === ts.SyntaxKind.PrivateKeyword))
      .map((m) => m.name?.getText(this.source))
      .filter(Boolean);
  }

  injected(node) {
    const ctor = node.members.find(ts.isConstructorDeclaration);
    if (!ctor) return [];
    return ctor.parameters
      .map((p) => p.type?.getText(this.source) ?? "")
      .flatMap((t) => t.replace(/\[\]|\s|\|/g, " ").split(" "))
      .filter((t) => /^[A-Z]/.test(t));
  }
}

class TypeBox {
  constructor(name, kind, methods, dependsOn) {
    this.name = name;
    this.kind = kind;
    this.methods = methods;
    this.dependsOn = dependsOn;
  }
}

class Diagram {
  constructor(modules) {
    this.modules = modules;
  }

  get boxes() {
    return this.modules.flatMap((m) => m.types.map((t) => ({ layer: m.layer, rel: m.rel, type: t })));
  }

  render() {
    const boxes = this.boxes;
    const known = new Set(boxes.map((b) => b.type.name));
    const layers = [...new Set(boxes.map((b) => b.layer))].sort(
      (a, b) => LAYER_ORDER.indexOf(a) - LAYER_ORDER.indexOf(b),
    );

    const lines = ["```mermaid", "classDiagram"];
    for (const layer of layers) {
      const inLayer = boxes.filter((b) => b.layer === layer);
      lines.push(`  namespace ${layer.replace(/[()]/g, "")} {`);
      for (const { type } of inLayer) {
        lines.push(`    class ${type.name} {`);
        if (type.kind === "interface") lines.push("      <<interface>>");
        for (const method of type.methods.slice(0, 8)) lines.push(`      ${method}()`);
        lines.push("    }");
      }
      lines.push("  }");
    }
    for (const { type } of boxes) {
      for (const dep of [...new Set(type.dependsOn)].filter((d) => known.has(d) && d !== type.name)) {
        lines.push(`  ${type.name} --> ${dep}`);
      }
    }
    lines.push("```");
    return lines.join("\n");
  }

  inventory() {
    const rows = ["| Layer | Module | Classes |", "|---|---|---|"];
    for (const m of this.modules.filter((m) => m.types.length)) {
      rows.push(`| \`${m.layer}\` | \`${m.rel}\` | ${m.types.map((t) => t.name).join(", ")} |`);
    }
    return rows.join("\n");
  }
}

class Scanner {
  read(dir = SRC) {
    return readdirSync(dir).flatMap((name) => {
      const full = join(dir, name);
      if (statSync(full).isDirectory()) return this.read(full);
      if (!name.endsWith(".ts")) return [];
      const rel = relative(SRC, full);
      const text = readFileSync(full, "utf8");
      return [new Module(rel, ts.createSourceFile(rel, text, ts.ScriptTarget.Latest, true))];
    });
  }
}

const diagram = new Diagram(new Scanner().read());
const body = [
  "# Class diagram",
  "",
  "Generated by `node server/scripts/class-diagram.mjs`. Do not hand-edit.",
  "",
  "Arrows are constructor dependencies: `A --> B` means A is given a B.",
  "",
  diagram.render(),
  "",
  "## Inventory",
  "",
  diagram.inventory(),
  "",
].join("\n");

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, body);
console.log(`wrote ${relative(join(HERE, "..", ".."), OUT)} — ${diagram.boxes.length} types`);
